* rip (Rm ImProved)
Deleted files get sent to the graveyard (=/tmp/.graveyard= by default) under their absolute path) instead of being unlinked, giving you a chance to recover them.

No data is overwritten.  If files that share the same path are deleted, they will be renamed as numbered backups.

If you want to put the graveyard somewhere else (like =~/.local/share/Trash=), you could alias =rip= to =rip --graveyard ~/.local/share/Trash=.  This can be a good idea because if the graveyard is in a tmpfs mount, deleting large files can quickly fill up your RAM.  It's also slower than moving files within the same filesystem.

** Installation
Get a binary [[https://github.com/nivekuil/rip/releases][release]] (x86_64) or =cargo install rm-improved=.

** Usage
#+BEGIN_EXAMPLE
USAGE:
    rip [FLAGS] [OPTIONS] <SOURCE>...

FLAGS:
        --decompose    Permanently delete (unlink) the entire graveyard
    -h, --help         Prints help information
    -r, --resurrect    Undo the last deletion
    -s, --seance       List all objects in the graveyard that were sent from the current directory
    -V, --version      Prints version information

OPTIONS:
        --graveyard <graveyard>    Directory where deleted files go to rest

ARGS:
    <SOURCE>...    File or directory to remove
#+END_EXAMPLE

*** Why is there no =--interactive= option?
Asking for forgiveness is easier than asking for permission.
