* rip (Rm ImProved)
A safer, (eventually) more powerful =rm= written in Rust.

Deleted files get sent to the graveyard (=/tmp/.graveyard=).  Their path is preserved, with all parent directories being created under the graveyard.

No data is overwritten.  If files that share the same path are deleted, they will be numbered backups courtesy of =mv(1)=.

If you want to put the graveyard somewhere else (like =~/.local/share/Trash=), you could alias =rip= to =rip --graveyard ~/.local/share/Trash=.
This can be a good idea because the graveyard is in /tmp by default, which can quickly fill up your RAM if /tmp is mounted as tmpfs.  It's also slower than moving files within the same filesystem.

** Installation
Get a binary [[https://github.com/nivekuil/rip/releases][release]] or clone the repository and run =cargo build=.

** Usage
#+BEGIN_EXAMPLE
USAGE:
    rip [OPTIONS] <TARGET>...

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
        --graveyard <graveyard>    Directory where deleted files go to rest

ARGS:
    <TARGET>...    File or directory to remove
#+END_EXAMPLE

*** Why is there no =--interactive= option?
Asking for forgiveness is easier than asking for permission.
