* rip (Rm ImProved)
[[https://crates.io/crates/rm-improved][https://img.shields.io/crates/v/rm-improved.svg]]

Deleted files get sent to the graveyard (=/tmp/.graveyard= by default, under their absolute path) instead of being unlinked, giving you a chance to recover them.

No data is overwritten.  If files that share the same path are deleted, they will be renamed as numbered backups.

If you want to put the graveyard somewhere else (like =~/.local/share/Trash=), you have two options, in order of precedence:
1. Alias =rip= to =rip --graveyard ~/.local/share/Trash=
2. Set the environment variable =$GRAVEYARD= to =~/.local/share/Trash=
This can be a good idea because if the graveyard is mounted on an in-memory filesystem, (as /tmp is in Arch Linux), deleting large files can quickly fill up your RAM.  It's also much slower to move files across filesystems, although the delay should be minimal with an SSD.

A deletion log is kept in =.rip_history=, found in the top level of the graveyard.

** Installation
Get a binary [[https://github.com/nivekuil/rip/releases][release]] (x86_64) or build it with =cargo install rm-improved= (requires a nightly version of rustc).

** Usage
#+BEGIN_EXAMPLE
USAGE:
    rip [FLAGS] [OPTIONS] [TARGET]...

FLAGS:
    -d, --decompose    Permanently delete (unlink) the entire graveyard
    -h, --help         Prints help information
    -i, --inspect      Print some info about TARGET before prompting for action
    -r, --resurrect    Undo the last removal by the current user
    -s, --seance       List all objects in the graveyard that were sent from the current directory
    -V, --version      Prints version information

OPTIONS:
        --graveyard <graveyard>    Directory where deleted files go to rest

ARGS:
    <TARGET>...    File or directory to remove
#+END_EXAMPLE

*** Notes
- In general, a deletion followed by a =--resurrect= should be idempotent.
- You probably shouldn't alias =rm= to =rip=.  =rm -r= is two characters longer, anyway.
